# LLM model
api_key: ""
model_id: dvue-aoai-001-gpt-5
temperature: 1.0

# dataloader
statis_path: "TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
py_folder: "TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_v1"
instruction_path: "TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "TB-eval/tb_eval/data/TritonBench/data/train_crawl.json"
golden_metrics: "TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: null
perf_G_path: ""
py_interpreter: "python"


# agent
result_path: null #Resuming from Checkpoints
mem_file: null #Resuming from Checkpoints
start_iter: 0
start_idx: 0
datalen: null
output_path: "../outputs/20251001_gaagent_offspring8_gpt5.jsonl"
max_iteration: 10
multi_thread: true
ancestor_num: 5   #ancestor number of perf_candidates used to generate descendant
descendant_num: 8 #offspring
gpu_id: 7
descendant_debug: 1 # if descendant_debug of descendant pass execution test, then generate descendant_num of new codes.
target_gpu: "MI200"
profiling: false # use profiling info.
