# LLM model
api_key: ""
model_id: "gemini-2.5-pro-preview-05-06"
temperature: 1.0

# TritonBench
statis_path: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
py_folder: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_v1"
instruction_path: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/data/TritonBench_G_comp_alpac_v1_fixed_with_difficulty.json"
corpus_path: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/data/train_crawl.json"
golden_metrics: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G/golden_metrics"
perf_ref_folder: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G/golden_results"
perf_G_path: "/group/ossdphi_algo_scratch_03/chaox/Documents/project/kernel_agent/TB-eval/tb_eval/data/TritonBench/performance_metrics/perf_G"
py_interpreter: "python"
result_path: null
mem_file: null
start_iter: 0

# agent
output_path: "../outputs/20250715_optimagent_kimi.jsonl"
max_iteration: 20
multi_thread: true
ancestor_num: 5